// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJRDczp8EI4RTC0GYGQ8QzFBXi8C-eEKY',
    appId: '1:831151109255:web:710a583d6531d8bac4b422',
    messagingSenderId: '831151109255',
    projectId: 'egalee-ce184',
    authDomain: 'egalee-ce184.firebaseapp.com',
    storageBucket: 'egalee-ce184.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD3chHhL31YaUUl7SF5zE5BtVZ7zwSMuU',
    appId: '1:831151109255:android:2e7806ba2dbc7e6ec4b422',
    messagingSenderId: '831151109255',
    projectId: 'egalee-ce184',
    storageBucket: 'egalee-ce184.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN1Mfi7-HqRAvhn6ZNZmaMZoGoA2FgKwY',
    appId: '1:831151109255:ios:2723ca11087d3de5c4b422',
    messagingSenderId: '831151109255',
    projectId: 'egalee-ce184',
    storageBucket: 'egalee-ce184.appspot.com',
    iosBundleId: 'com.example.egaleeAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN1Mfi7-HqRAvhn6ZNZmaMZoGoA2FgKwY',
    appId: '1:831151109255:ios:fa3450e79177398fc4b422',
    messagingSenderId: '831151109255',
    projectId: 'egalee-ce184',
    storageBucket: 'egalee-ce184.appspot.com',
    iosBundleId: 'com.example.egaleeAdmin.RunnerTests',
  );
}
